module WindowConstants

	private
	TITLE_FONT_HEIGHT = 20
	TITLE_CHARACTER_WIDTH = 13

	TITLE_SIZE_ENUM = 3

	TOP_PADDING = 20
	SIDE_PADDING = 20
	BOTTOM_PADDING = 20

	EXIT_SIZE = [25, 25]
	DEFAULT_BUTTON_WIDTH = 100
	DEFAULT_BUTTON_HEIGHT = 50

end